use std::fs;
use std::path::Path;

fn main() {
    let cert_dir = Path::new("../certs");
    let cert_path = cert_dir.join("server_cert.pem");
    let key_path = cert_dir.join("server_key.pem");
    let pin_path = cert_dir.join("spki_pin.txt");

    assert!(
        cert_path.exists(),
        "Certs not found. Run ./generate-certs.sh first!"
    );

    fs::copy(&cert_path, "embedded_cert.pem").expect("Failed to copy cert");
    fs::copy(&key_path, "embedded_key.pem").expect("Failed to copy key");
    fs::copy(&pin_path, "spki_pin.txt").expect("Failed to copy pin");

    println!("cargo:rerun-if-changed={}", cert_path.display());
    println!("cargo:rerun-if-changed={}", key_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();

    // Always write the embedded module so lib.rs can include! it on all targets.
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let embedded_path = Path::new(&out_dir).join("webview2_embedded.rs");

    let dll_path = Path::new("WebView2Loader.dll");
    if target_os == "windows" && dll_path.exists() {
        // Step 1: Link the delay-import library (generated by CI using dlltool -y)
        let delaylib_dir = dll_path.parent().unwrap_or(Path::new("."));
        let delaylib = delaylib_dir.join("delaylib");
        if delaylib.exists() {
            println!("cargo:rustc-link-search={}", delaylib.display());
        }

        // Step 2: Link delayimp for __delayLoadHelper2
        println!("cargo:rustc-link-lib=delayimp");

        // Step 3: Embed DLL bytes for runtime extraction
        let bytes = fs::read(dll_path).expect("Failed to read WebView2Loader.dll");
        let mut code = String::from("pub const WEBVIEW2_LOADER_DLL: &[u8] = &[\n");
        for chunk in bytes.chunks(16) {
            code.push_str("    ");
            for (j, byte) in chunk.iter().enumerate() {
                if j > 0 { code.push_str(", "); }
                code.push_str(&format!("0x{:02x}", byte));
            }
            code.push_str(",\n");
        }
        code.push_str("];\n");
        fs::write(&embedded_path, code).expect("Failed to write embedded dll");
        println!("cargo:rerun-if-changed=WebView2Loader.dll");
    } else {
        // Non-Windows or no DLL — stub (empty, dead code on non-Windows)
        fs::write(&embedded_path, "pub const WEBVIEW2_LOADER_DLL: &[u8] = &[];\n")
            .expect("Failed to write stub");
    }

    tauri_build::build();
}
